#!/bin/bash

echo "*** Adding all changed files.\n\r"
git add --all

echo "***** Committing changes to local repository"
git commit -am "$1"

echo "******* Updating remote github repository"
git push origin master

